### ISSUE TITLE
Deprecated selector in `darkpython-syntax/index.less`

### ISSUE THREAD

**Issue by EagleOne42** [tryexceptpass/darkpython-syntax#4]
Using Atom 1.14.4 x64 Linux
darkpython-syntax 0.4.2

Not sure if there were more fixes planned, but after updating this today this is still reporting some deprecated selectors.

In `darkpython-syntax/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `.syntax--keyword.syntax--operator.logical` => `.syntax--keyword.syntax--operator.syntax--logical`

* `.syntax--punctuation.section.embedded` => `.syntax--punctuation.syntax--section.syntax--embedded`

* `.syntax--entitysyntax--.other.syntax--attribute-name` => `.syntax--entitysyntax--.syntax--other.syntax--attribute-name`

* `.syntax--entitysyntax--.other.syntax--attribute-name.syntax--id` => `.syntax--entitysyntax--.syntax--other.syntax--attribute-name.syntax--id`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by EagleOne42** [comment]
Pulled an update today and it was no longer reported.  Thanks for this!

**Comment by tryexceptpass** [comment]
Yep no problem, thanks to @alton-campbell for making the fixes.
